# Generated by Django 4.1.2 on 2022-10-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_photos'),
        ),
    ]
